version: 1.1
source:
    notes: |
        tsv, with some sed originally
    dir: /home/tac/g/survos/anki/data
    include: /*.tsv/
    url: https://dl.opensubtitles.org/addons/export/

files:
    /title_basics/: movie
tables:
    title_basics:
        indexes:
            - code|text
            - type
            - year
            - minutes|int
#            - genre
            - is_adult|bool
        # these are the column rules
        rules:
#            /accession_number/: code
            /tconst/: code
            /titleType/: type
            /startYear/: year
            /primaryTitle/: title
            /runtimeMinutes/: minutes # hmm, minutes|int seems better, without index
            /isAdult/: is_adult
            # by default, parse if it starts with [ or {
#            /genres,/: genre
#            /artists[{}]/: artists
#            /dimensions{}/: dimensions
            # from https://csv.thephpleague.com/9.0/writer/
#            $formatter = function (array $row): array {
#                return array_map('strtoupper', $row);
#    };
#        $writer = Writer::createFromFileObject(new SplTempFileObject());
#        $writer->addFormatter($formatter);
        # maybe someday: https://symfony.com/doc/current/components/expression_language.html
        formatter:
            //: # match everything
                /\\N/: ''
            /is_/:
                /1/: true
                /0/: false
