
survos_pixie:
  # directories are relative to the project dir if not prefixed with /

  # location of the .pixie files.  Add to .gitignore to prevent checkin if in the repo path
  extension: .pixie.sqlite
  db_dir: pixie
  # path for csv and json data.
  data_root: data
  # location of the .config.yaml files
  config_dir: config/packages/pixie
  purge_before_import: true
  pixies:
    cleveland:
      version: 1.1
#      source:
#        instructions: |
#          cd data && \
#          git clone git@github.com:ClevelandMuseumArt/openaccess.git cleveland && cd cleveland && \
#          git lfs pull --include=data.json
#        notes: |
#          The JSON feed has more and better data, e.g. measurements broken out,
#          and exhibitions in a JSON list, artist id.
#          But it is more complicated to change property names of JSON
#        dir: ../data/cleveland
#        ignore: /csv/
#        include: "*.json"

