imports:
  - { resource: pixie/walters.yaml }
  - { resource: pixie/mexmus.yaml }
  # If you want to import a whole directory:
  # - { resource: services/ }

survos_pixie:

  # location of the .pixie files.  Add to .gitignore to prevent checkin if in the repo path
  extension: .pixie.sqlite
  # directories are relative to the project dir if not prefixed with /
  db_dir: pixie

  # path for csv and json data.
  data_root: data
  # location of the .config.yaml files
  config_dir: config/packages/pixie
  purge_before_import: true
  pixies:
    cleveland:
      code: cleveland
      version: 1.1
      source:
        git:
          repo: ClevelandMuseumArt/openaccess
          lfs: true
          lsf_include: data.json
#        build:
#          - action: fetch
#            source: https://www.imls.gov/sites/default/files/2018_csv_museum_data_files.zip
#            target: data/mdf
#            unzip: data/mdf
#          - action: cmd
#            cmd: 'bunny:upload /data/%code%'
        instructions: |
          cd data && \
          git clone git@github.com:ClevelandMuseumArt/openaccess.git cleveland && cd cleveland && \
          git lfs pull --include=data.json
          bin/console pixie:import cleveland
        notes: |
          The JSON feed has more and better data, e.g. measurements broken out,
          and exhibitions in a JSON list, artist id.
          But it is more complicated to change property names of JSON
        dir: ../data/cleveland
        ignore: /csv/
        include: "*.json"

