tables:
  image:
#    workflow: ImageWorkflow
#    parent: artwork
    properties:
      - id:int
      - marking:text#
      - local # relative to datadir?  Need to download to upload to flickr, but not to s3
      - status:text#
      # these are not mapped from the initial fields, but added later
      - flickr_id:text## # browsable=false
      - content_hash:text##  # of the actual file
      - marking:text#
      - record_type:text#
      - cover_accession_number:text#
      - artwork_id:rel.artwork
