version: 1.1
source:
    notes: |
        tsv, with some sed originally
    dir: /home/tac/g/survos/anki/data
    include: /*.tsv/
    url: https://dl.opensubtitles.org/addons/export/
    # imdb: https://datasets.imdbws.com/

files:
    /subtitles/: subtitles
tables:
    subtitles:
        rules:
#            /accession_number/: code
            /IDSubtitle/: code
            /MovieYear/: year
            /MovieName/: title
            /MovieKind/: type
            /ISO639/: language
            /ImdbID/: imdbId
        properties:
            - code:text
            - type:text#
            - language:text#
            - imdbId:int#
            - name: year
              type: int
              index: movie_year_index
        # these are the column rules
        formatter:
            /is_/:
                /1/: true
                /0/: false
