version: 1.1
source:
    instructions: cd data && git clone git@github.com:ClevelandMuseumArt/openaccess.git cma && cd cma && git lfs pull
    notes: |
        
        
        The JSON feed has more and better data, e.g. measurements broken out,
        and exhibitions in a JSON list, artist id.
        But it is more complicated to change property names of JSON
    dir: /home/tac/g/museado/data/cma # relative to data_dir
    ignore: /report|csv/
    include: /*.json/
    github: https://github.com/ClevelandMuseumArt/openaccess

files:
    /data/: artwork
tables:
    artwork:
        rules:
            /accession_number/: code
            /share_license_status/: license
        properties:
            - id
            - code
            - license:text#
#        indexes:
#            - accession_number|text
#            - license
#            - technique
#            - culture
