version: 1.1
source:
    url: https://sic.cultura.gob.mx/opendata/d/0_museo_directorio.json
    # mkdir -p data/mexmus && curl "https://sic.cultura.gob.mx/opendata/d/0_museo_directorio.json" -o data/mexmus/0_museo_directorio.json
#    dir: mexmus
/*/:
    rules:
        /password/: '!'
    ignore:
        - /password/i
files:
    /museo_directorio/: museos

tables:
    museos:
        indexes: 'id|INTEGER,nom_loc,tema,propiedad'
        rules:
            /museo_id/: id
            /museo_nombre/: nombre
            /museo_tematica_n1/: tema
            /nom_loc/: loc
            /museo_tipo_de_propiedad/: propiedad

# parser rules for the data
formatters:
    //
