version: '1.1'
source:
    dir: data/moma/ # relative to project dir.  data_dir is only for the default, when this doesn't exist
    locale: en
    include: '*.json'
    ignore: '*.csv'
files:
    /Artists/: artist
    /Artworks/: artwork
tables:
#    - name: artwork
#      columns:
#          - name: abc
#      rules:
#              /ObjectID/i: id
#              /BeginDate/: artistBirthYear
#
#
#x:
    artwork:
#        indexes: 'id|int,department,classification,year|int'
        # column header rules.  Use rulesets?  Allow type or require in properties?
        rules:
            /ObjectID/i: id
            /BeginDate/: artistBirthYear
            /EndDate/: artistDeathYear
            /^Date$/: art_year
            /^Date_Acquired/: year_acquired
            /ConstituentID/: artist_id  # this rule ONLY applied in artwork.  Bug
        # could come from SQL or created during the import
        # if there's a match, move the data here.  Everything else goes in _attributes
        properties:
            - id:int
            - artistBirthYear:int
            - | 
                department: 
                    filterable: true
                    indexed: true
                    type: string
            - |
                birthYear: 
                    filterable: false
                    indexed: true
                    type: string
                    


        # additional columns
        columns:
            -   name: isAlive
                type: bool
                value: row.artistDeathYear == 0
            -   name: decade
                type: int
                value: row.year % 10 == 0
        indexes:
            - id|INTEGER
            - department
            - classification
            - art_year|INTEGER
            - date_acquired|DATETIME # hint only, but can get during in the sql https://stackoverflow.com/questions/17227110/how-do-datetime-values-work-in-sqlite
    #            - description|SEARCHTEXT,translatable

    artist:
        # renaming rules
        rules:
            /ConstituentID/: id
            /BeginDate/: birthYear
            /EndDate/: deathYear
        # additional/enhanced properties, based on renamed rules
        properties:
            - status:string
            - wiki_qid:string
        #             - '&qid'
        # used by renaming rules
        indexes:
            - id|INTEGER
            - nationality
            - birth_year|INTEGER
            - gender
