version: 1.1
source:
    dir: data/moma/ # relative to project dir.  data_dir is only for the default, when this doesn't exist
    locale: en
    include: '*.json'
    ignore: '*.csv'
files:
    /Artists/: artist
    /Artworks/: artwork
tables:
    artwork:
#        indexes: 'id|int,department,classification,year|int'
        indexes:
            - id|INTEGER
            - department
            - classification
            - art_year|INTEGER
            - date_acquired|DATETIME # hint only, but can get during in the sql https://stackoverflow.com/questions/17227110/how-do-datetime-values-work-in-sqlite
#            - description|SEARCHTEXT,translatable
        # column header rules.  Use rulesets?
        rules:
            /ObjectID/i: id
            /BeginDate/: artistBirthYear
            /EndDate/: artistDeathYear
            /^Date$/: art_year
#            /^Date_Acquired/: art_year
            /ConstituentID/: artist_id  # this rule ONLY applied in artwork.  Bug
        # could come from SQL or created during the import
        virtualColumns:
            - isAlive:
                type: bool
                value: row.artistDeathYear == 0
            - decade:
                type: int
                value: row.year % 10 == 0

    artist:
        indexes:
            - id|INTEGER
            - nationality
            - birth_year|INTEGER
            - gender
        properties: # extracted from json as virtual columns
            - wiki_qid
#             - '&qid'
        rules:
            /ConstituentID/: id
            /BeginDate/: birthYear
            /EndDate/: deathYear
